import fs from "node:fs/promises";
import path from "node:path";
import { ARTIFACT_PATHS } from "../artifacts/artifact-paths.js";

export interface WorkerContextPack {
  version: 1;
  jobId: string;
  task: string;
  generatedAt: string;
  summary: string;
  relevantFiles: WorkerContextFile[];
  allowedDiffBoundary: string[];
  doNotTouch: string[];
  conventions: WorkerRepoConventions;
  implementationPlan: string[];
  verificationCommands: string[];
  assumptions: string[];
  missingContextWarnings: string[];
  confidence: "low" | "medium" | "high";
}

export interface WorkerContextFile {
  path: string;
  reason: string;
  status: "existing" | "proposed";
  role:
    | "entrypoint"
    | "component"
    | "hook"
    | "service"
    | "api-client"
    | "backend-route"
    | "test"
    | "config"
    | "unknown";
}

export interface WorkerRepoConventions {
  screenPatterns?: string[];
  componentPatterns?: string[];
  hookPatterns?: string[];
  servicePatterns?: string[];
  apiClientPatterns?: string[];
  testPatterns?: string[];
  notes?: string[];
}

export async function loadWorkerContextPack(artifactDir: string): Promise<WorkerContextPack | null> {
  try {
    const raw = await fs.readFile(path.join(artifactDir, ARTIFACT_PATHS.contextPack), "utf8");
    return normalizeWorkerContextPack(JSON.parse(raw), { jobId: "", task: "" });
  } catch {
    return null;
  }
}

export async function saveWorkerContextPack(artifactDir: string, pack: WorkerContextPack): Promise<void> {
  await saveContextPackArtifacts(artifactDir, pack, ARTIFACT_PATHS.contextPack, ARTIFACT_PATHS.contextPackMarkdown);
}

export async function savePreContextPack(artifactDir: string, pack: WorkerContextPack): Promise<void> {
  await saveContextPackArtifacts(artifactDir, pack, ARTIFACT_PATHS.preContextPack, ARTIFACT_PATHS.preContextPackMarkdown);
}

export function normalizeWorkerContextPack(
  raw: unknown,
  fallback: { jobId: string; task: string }
): WorkerContextPack {
  const source = raw && typeof raw === "object" ? raw as Record<string, unknown> : {};
  const confidence = source.confidence === "high" || source.confidence === "medium" || source.confidence === "low"
    ? source.confidence
    : "low";

  return {
    version: 1,
    jobId: stringValue(source.jobId, fallback.jobId),
    task: stringValue(source.task, fallback.task),
    generatedAt: stringValue(source.generatedAt, new Date().toISOString()),
    summary: stringValue(source.summary, "Context pack was not fully generated by the setup phase."),
    relevantFiles: normalizeRelevantFiles(source.relevantFiles),
    allowedDiffBoundary: normalizeStringArray(source.allowedDiffBoundary),
    doNotTouch: normalizeStringArray(source.doNotTouch),
    conventions: normalizeConventions(source.conventions),
    implementationPlan: normalizeStringArray(source.implementationPlan),
    verificationCommands: normalizeStringArray(source.verificationCommands),
    assumptions: normalizeStringArray(source.assumptions),
    missingContextWarnings: normalizeStringArray(source.missingContextWarnings),
    confidence
  };
}

export function createFallbackWorkerContextPack(input: {
  jobId: string;
  task: string;
  warning: string;
}): WorkerContextPack {
  return normalizeWorkerContextPack({
    jobId: input.jobId,
    task: input.task,
    generatedAt: new Date().toISOString(),
    summary: "Setup phase did not provide a valid context pack.",
    relevantFiles: [],
    allowedDiffBoundary: [],
    doNotTouch: [],
    conventions: {},
    implementationPlan: [],
    verificationCommands: [],
    assumptions: [],
    missingContextWarnings: [input.warning],
    confidence: "low"
  }, input);
}

export function renderWorkerContextPackMarkdown(pack: WorkerContextPack): string {
  return [
    "# Worker Context Pack",
    "",
    `- Job ID: ${pack.jobId || "(unknown)"}`,
    `- Confidence: ${pack.confidence}`,
    `- Generated: ${pack.generatedAt}`,
    "",
    "## Summary",
    "",
    pack.summary || "(none)",
    "",
    "## Relevant Files",
    "",
    renderContextFiles(pack.relevantFiles),
    "",
    "## Allowed Diff Boundary",
    "",
    renderList(pack.allowedDiffBoundary),
    "",
    "## Do Not Touch",
    "",
    renderList(pack.doNotTouch),
    "",
    "## Implementation Plan",
    "",
    renderList(pack.implementationPlan),
    "",
    "## Verification Commands",
    "",
    renderList(pack.verificationCommands),
    "",
    "## Assumptions",
    "",
    renderList(pack.assumptions),
    "",
    "## Missing Context Warnings",
    "",
    renderList(pack.missingContextWarnings),
    "",
    "## Conventions",
    "",
    renderConventions(pack.conventions),
    ""
  ].join("\n");
}

function normalizeRelevantFiles(value: unknown): WorkerContextFile[] {
  if (!Array.isArray(value)) return [];
  return value
    .map((entry) => entry && typeof entry === "object" ? entry as Record<string, unknown> : null)
    .filter((entry): entry is Record<string, unknown> => Boolean(entry))
    .map((entry): WorkerContextFile => ({
      path: stringValue(entry.path, ""),
      reason: stringValue(entry.reason, ""),
      status: entry.status === "proposed" ? "proposed" : "existing",
      role: normalizeRole(entry.role)
    }))
    .filter((entry) => entry.path.length > 0);
}

function normalizeConventions(value: unknown): WorkerRepoConventions {
  const source = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return {
    screenPatterns: normalizeStringArray(source.screenPatterns),
    componentPatterns: normalizeStringArray(source.componentPatterns),
    hookPatterns: normalizeStringArray(source.hookPatterns),
    servicePatterns: normalizeStringArray(source.servicePatterns),
    apiClientPatterns: normalizeStringArray(source.apiClientPatterns),
    testPatterns: normalizeStringArray(source.testPatterns),
    notes: normalizeStringArray(source.notes)
  };
}

function normalizeRole(value: unknown): WorkerContextFile["role"] {
  const allowed = new Set<WorkerContextFile["role"]>([
    "entrypoint",
    "component",
    "hook",
    "service",
    "api-client",
    "backend-route",
    "test",
    "config",
    "unknown"
  ]);
  return typeof value === "string" && allowed.has(value as WorkerContextFile["role"])
    ? value as WorkerContextFile["role"]
    : "unknown";
}

function normalizeStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((entry) => typeof entry === "string" ? entry.trim() : "").filter(Boolean);
}

function stringValue(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function renderContextFiles(files: WorkerContextFile[]): string {
  if (files.length === 0) return "- (none)";
  return files.map((file) => `- \`${file.path}\` (${file.status}, ${file.role}): ${file.reason || "No reason provided."}`).join("\n");
}

function renderList(values: string[]): string {
  if (values.length === 0) return "- (none)";
  return values.map((value) => `- ${value}`).join("\n");
}

function renderConventions(conventions: WorkerRepoConventions): string {
  const entries = Object.entries(conventions)
    .filter(([, values]) => Array.isArray(values) && values.length > 0)
    .map(([key, values]) => `- ${key}: ${(values as string[]).join(", ")}`);
  return entries.length > 0 ? entries.join("\n") : "- (none)";
}

async function saveContextPackArtifacts(
  artifactDir: string,
  pack: WorkerContextPack,
  jsonPath: string,
  markdownPath: string
): Promise<void> {
  await fs.mkdir(path.dirname(path.join(artifactDir, jsonPath)), { recursive: true });
  await Promise.all([
    fs.writeFile(path.join(artifactDir, jsonPath), `${JSON.stringify(pack, null, 2)}\n`, "utf8"),
    fs.writeFile(path.join(artifactDir, markdownPath), renderWorkerContextPackMarkdown(pack), "utf8")
  ]);
}
